apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: ragdb
    user: raguser
    secureJsonData:
      password: ragpass
    isDefault: true
    jsonData:
      sslmode: disable
